### ISSUE TITLE
[BUG] code review found 17 items only commented 3 on PR

### ISSUE THREAD

**Issue by joelsprunger** [mattzcarey/shippie#328]
### Current Behavior:
I added LangSmith tracing to my github action.
```yml
    env:
      LANGCHAIN_TRACING_V2: "true"
      LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      LANGCHAIN_PROJECT: "code_review_gpt"
```
In looking over the traces outputs for my large PR, I see 17 comments in 5 or 6 groups. However the Summary chain to generate emojis) only has 3 of these comments as input. These are the ones that go to the PR comments. The other 15 seem to be discarded.
 
### Expected Behavior:
The PR comments should contain **ALL** the Risk items found in code review. Perhaps the emoji summarizer needs to randomly select the comments to add, or add a finite number of comments prioritized by risk level.

### Steps To Reproduce:
Hmm. Tough. Big PR. Check the tracing.

### Suggestions on the root cause
I am guessing the root cause is the finite context window for the summary. You can still limit the comments used in the summary, but add **ALL** comments to the PR.
